name: Publish

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - run: echo ${GITHUB_REF##*/}
      - name: Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm t
      - run: npm version ${GITHUB_REF##*/} -git-tag-version false
      - name: Build
        run: npm run build
      - name: Publish
        run: npm publish --access public
      - name: Commit Changes
        run: git add . && git commit -m "release ${GITHUB_REF##*/}" && git push
