name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm ci
      - name: Run Linter
        run: npm run lint
      - name: Run Typechecker
        run: npm run typecheck
      - name: Run Tests
        run: npm t
      - name: Coverage to Codecov
        run: node ./node_modules/codecov/bin/codecov
      # - name: Coverage to Codacy
      #   uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        env:
          CODECOV_TOKEN: "2ac0ef32-0494-4b52-89f1-decc18cfd628"
